
#pragma once


#include <eglbinding/eglbinding_features.h>

#include <eglbinding/noegl.h>
#include <eglbinding/egl/types.h>


namespace egl
{


EGLBINDING_CONSTEXPR static const EGLNativeDisplayType EGL_DEFAULT_DISPLAY = EGL_CAST(EGLNativeDisplayType,0);
EGLBINDING_CONSTEXPR static const EGLint EGL_DEPTH_ENCODING_NONE_NV = 0;
EGLBINDING_CONSTEXPR static const EGLint EGL_DISPLAY_SCALING = 10000;
EGLBINDING_CONSTEXPR static const EGLint EGL_DONT_CARE = EGL_CAST(EGLint,-1);
EGLBINDING_CONSTEXPR static const EGLuint64KHR EGL_FOREVER = 0xFFFFFFFFFFFFFFFF;
EGLBINDING_CONSTEXPR static const EGLuint64KHR EGL_FOREVER_KHR = 0xFFFFFFFFFFFFFFFF;
EGLBINDING_CONSTEXPR static const EGLuint64KHR EGL_FOREVER_NV = 0xFFFFFFFFFFFFFFFF;
EGLBINDING_CONSTEXPR static const EGLConfig EGL_NO_CONFIG_KHR = EGL_CAST(EGLConfig,0);
EGLBINDING_CONSTEXPR static const EGLContext EGL_NO_CONTEXT = EGL_CAST(EGLContext,0);
EGLBINDING_CONSTEXPR static const EGLDeviceEXT EGL_NO_DEVICE_EXT = EGL_CAST(EGLDeviceEXT,0);
EGLBINDING_CONSTEXPR static const EGLDisplay EGL_NO_DISPLAY = EGL_CAST(EGLDisplay,0);
EGLBINDING_CONSTEXPR static const EGLNativeFileDescriptorKHR EGL_NO_FILE_DESCRIPTOR_KHR = EGL_CAST(EGLNativeFileDescriptorKHR,-1);
EGLBINDING_CONSTEXPR static const EGLImage EGL_NO_IMAGE = EGL_CAST(EGLImage,0);
EGLBINDING_CONSTEXPR static const EGLImageKHR EGL_NO_IMAGE_KHR = EGL_CAST(EGLImageKHR,0);
EGLBINDING_CONSTEXPR static const EGLOutputLayerEXT EGL_NO_OUTPUT_LAYER_EXT = EGL_CAST(EGLOutputLayerEXT,0);
EGLBINDING_CONSTEXPR static const EGLOutputPortEXT EGL_NO_OUTPUT_PORT_EXT = EGL_CAST(EGLOutputPortEXT,0);
EGLBINDING_CONSTEXPR static const EGLStreamKHR EGL_NO_STREAM_KHR = EGL_CAST(EGLStreamKHR,0);
EGLBINDING_CONSTEXPR static const EGLSurface EGL_NO_SURFACE = EGL_CAST(EGLSurface,0);
EGLBINDING_CONSTEXPR static const EGLSync EGL_NO_SYNC = EGL_CAST(EGLSync,0);
EGLBINDING_CONSTEXPR static const EGLSyncKHR EGL_NO_SYNC_KHR = EGL_CAST(EGLSyncKHR,0);
EGLBINDING_CONSTEXPR static const EGLSyncNV EGL_NO_SYNC_NV = EGL_CAST(EGLSyncNV,0);
EGLBINDING_CONSTEXPR static const EGLint EGL_UNKNOWN = EGL_CAST(EGLint,-1);


} // namespace egl